export const mockFilms = [
  {
    backgroundColor: '#D8D3BD',
    backgroundImage: 'https://7.react.pages.academy/static/film/background/Orlando.jpg',
    description: 'Young nobleman Orlando is commanded by Queen Elizabeth I to stay forever young. Miraculously, he does just that. The film follows him as he moves through several centuries of British history, experiencing a variety of lives and relationships along the way, and even changing sex.',
    director: 'Sally Potter',
    genre: 'Action',
    id: 1,
    isFavorite: false,
    name: 'Orlando',
    posterImage: 'https://7.react.pages.academy/static/film/poster/Orlando.jpg',
    previewImage: 'https://7.react.pages.academy/static/film/preview/orlando.jpg',
    previewVideoLink: 'https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4',
    rating: 2.6,
    released: 1992,
    runTime: 94,
    scoresCount: 12292,
    starring: ['Tilda Swinton', 'Billy Zane', 'Quentin Crisp'],
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
  },
  {
    backgroundColor: '#C6CADF',
    backgroundImage: 'https://7.react.pages.academy/static/film/background/Seven_Years_in_Tibet.jpg',
    description: 'True story of Heinrich Harrer, an Austrian mountain climber who became friends with the Dalai Lama at the time of Chinas takeover of Tibet.',
    director: 'Jean-Jacques Annaud',
    genre: 'Adventure',
    id: 2,
    isFavorite: false,
    name: 'Seven Years in Tibet',
    posterImage: 'https://7.react.pages.academy/static/film/poster/Seven_Years_in_Tibet.jpg',
    previewImage: 'https://7.react.pages.academy/static/film/preview/seven-years-in-tibet.jpg',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
    rating: 3.6,
    released: 1997,
    runTime: 136,
    scoresCount: 112612,
    starring: ['Brad Pitt', 'David Thewlis', 'BD Wong'],
    videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
  },
  {
    backgroundColor: '#73B39A',
    backgroundImage: 'https://7.react.pages.academy/static/film/background/bronson.jpg',
    description: 'A young man who was sentenced to seven years in prison for robbing a post office ends up spending three decades in solitary confinement. During this time, his own personality is supplanted by his alter-ego, Charles Bronson.',
    director: 'Nicolas Winding Refn',
    genre: 'Action',
    id: 3,
    isFavorite: false,
    name: 'Bronson',
    posterImage: 'https://7.react.pages.academy/static/film/poster/bronson.jpg',
    previewImage: 'https://7.react.pages.academy/static/film/preview/bronson.jpg',
    previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
    rating: 3.6,
    released: 2008,
    runTime: 92,
    scoresCount: 109661,
    starring: ['Tom Hardy', 'Kelly Adams', 'Luing Andrews'],
    videoLink: 'http://media.xiph.org/mango/tears_of_steel_1080p.webm',
  },
];

export const mockFilm = {
  backgroundColor: '#C6CADF',
  backgroundImage: 'https://7.react.pages.academy/static/film/background/Seven_Years_in_Tibet.jpg',
  description: 'True story of Heinrich Harrer, an Austrian mountain climber who became friends with the Dalai Lama at the time of Chinas takeover of Tibet.',
  director: 'Jean-Jacques Annaud',
  genre: 'Adventure',
  id: 2,
  isFavorite: false,
  name: 'Seven Years in Tibet',
  posterImage: 'https://7.react.pages.academy/static/film/poster/Seven_Years_in_Tibet.jpg',
  previewImage: 'https://7.react.pages.academy/static/film/preview/seven-years-in-tibet.jpg',
  previewVideoLink: 'https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm',
  rating: 3.6,
  released: 1997,
  runTime: 136,
  scoresCount: 112612,
  starring: ['Brad Pitt', 'David Thewlis', 'BD Wong'],
  videoLink: 'http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4',
};

export const mockReviews = [
  {
    comment: 'Unfortunately we dont have a reliable way to tell the true ratings of a movie.',
    date: '2021-06-13T16:51:35.253Z',
    id: 1,
    rating: 7.4,
    userId: 18,
    userName: 'Sophie',
  },
  {
    comment: 'Poised to be an instant classic, almost everything about this film is phenomenal - the acting, the cinematography, the discography, etc.',
    date: '2021-06-19T16:51:35.253Z',
    id: 2,
    rating: 8.4,
    userId: 13,
    userName: 'Zak',
  },
];

export const mockReviewResponse = {
  'id': 1,
  'user': {
    'id': 4,
    'name': 'Kate Muir',
  },
  'rating': 8.9,
  'comment': 'Discerning travellers and Wes Anderson fans will luxuriate in the glorious Mittel-European kitsch of one of the directors funniest and most exquisitely designed movies in years.',
  'date': '2019-05-08T14:13:56.569Z',
};

export const mockReviewRequest = {
  'rating': 8,
  'comment': 'Discerning travellers and Wes Anderson fans will luxuriate in the glorious Mittel-European kitsch of one of the directors funniest and most exquisitely designed movies in years.',
};
